### ISSUE TITLE
Suggestions to improve docs

### ISSUE THREAD

**Issue by bt3gl** [zapatacomputing/orquestra-docs#15]
### Hi folks, these are some suggestions from my *newbie-experience* so far:

- [ ] Add more details and examples on what the (mandatory) `schema` field can be in the artifacts. What are the possible types of artifacts? How customizable is this field? From the first example, we know we can use `"message"`, what other schemas are available?

---

- [ ] In https://www.orquestra.io/docs/tutorial/helloworkflow/#building-a-resource, it appears we are repeating the description of `src` and `templates`. Maybe we can put all together?

---

- [ ] On the same page, why do we need `python/orquestra/`  instead of just `python/`? If we want to introduce such a dir structure we should be careful about adding `__init__.py` everywhere and what we define inside `setup.py`. For instance, perhaps we should make it explicit that everything is going to be found because of this line in `setup.py`:

```
 packages = setuptools.find_packages(where = "python")
```

Also, note that the [H2-vqe example](https://www.orquestra.io/docs/tutorial/hydrogen-vqe/) does not have this structure, but rather `src/python_file.py`.

---

- [ ] In the same page, we should make clear how we install external libraries in `setup.py` (item **5. Adding a setup.py**), e.g., we could explicitly add an example, something like:
```
    install_requires = [
       "urllib3",
       "requests",
   ],
```

---

- [ ] I want to ask you all more details about some privacy concerns about having a public Github repo for the work. I understand that the custom workflow (*workflow template*) is not needed to be committed and also the public repo is needed because this is how the code is pulled by QE. However,  this could be an issue for private research? If we are not planning to circumvent this, maybe we should give more details about this in the documentation (for the security geeks out there 😅).

---

- [x] There is an extra`**` in https://www.orquestra.io/docs/tutorial/helloworkflow/ and in https://www.orquestra.io/docs/tutorial/hydrogen-vqe/:

Submit your welcome-workflow.yaml by running qe submit workflow <path/to/workflow/welcome-workflow.yaml>**

and

Submit your hartree-fock-workflow.yaml by running qe submit workflow <path/to/workflow/hartree-fock-workflow.yaml>**

---

- [ ] It could be worth to explicitly explain what are the items in the `resources` list in the  `templates` section of a workflow (e.g., the python file names? why is it a list? etc.):
```
          parameters:
          - resources: [welcome]
```

---

- [ ] Inside https://www.orquestra.io/docs/qe/workflow/workflows/#arguments, perhaps it could be worth explaining artifacts' variables in more details (i.e., how to access them, what is available to be accessed, etc.), such as outputs
```
'{{steps.greeting.outputs.artifacts.welcome}}'
```
and inputs (where they need to be declared and how?):
```
   inputs:
      parameters:
      - name: species1
```

```
      artifacts:
        raw:
          data: |
            import json
            from diatomicmolecule import create_diatomic_molecule_geometry
            geometry = create_diatomic_molecule_geometry('{{inputs.parameters.species1}}'}) 
```

----

- [x] In that same page, there is a typo: 
```
In the example below, we define a template named salutaions 
```
            
----

- [ ] Is there a way to list *all/every* workflows I have submitted? For instance, what if I want to look at something from three days ago but I don't remember the `workflowID`?

---

- [ ] When talking about waiting for workflow results, maybe suggest the use of `watch`? Maybe we could add it here https://www.orquestra.io/docs/qe/cli/workflowresults/, since we say *"Run this command every two minutes until you get a link to download the results"*.

---

- [ ] The workflow results for VQE should not have the prefix `welcome-to-orquestra`.

--- 

- [x]  In https://www.orquestra.io/docs/qe/workflow/resources/#how-do-i-build-my-own-resource, the tree is ill-formatted. 

---

- [ ] In https://www.orquestra.io/docs/qe/workflow/resources/#initialization-file, the statement is not completely correct (`__init__.py` can be empty and the functions would still be able to be imported: the role of this file is to be a placeholder for the dir structure).

---

- [ ] Steps, conditionals, loops are soo cool! https://www.orquestra.io/docs/qe/workflow/steps/ We need a practical example of them!

- [ ] In the same way, we need more examples for using ML libs/docker images, as initially described in here https://www.orquestra.io/docs/qe/machine-learning/ml/ 😍 

A platform engineer question: how to we update and upgrade this list?

---

- [ ] We could add more information on how to debug our jobs in case it fails. For instance, we could add the command below somewhere:
```
qe get logs <workflowID> -s <stepID>
```

I see this command is available at https://www.orquestra.io/docs/qe/cli/logs/, but perhaps we want to add to the examples as well? (maybe not...)

---

**Comment by jama22** [comment]
hope you don't mind but i changed the bullet points into checkboxes so we could address them individually if we patch them

**Comment by jama22** [comment]
fixed some of the typos and formatting in https://github.com/zapatacomputing/orquestra-docs/pull/16
