### ISSUE TITLE
Broken link in Variational Loops

### ISSUE THREAD

**Issue by 1ethanhansen** [zapatacomputing/orquestra-docs#24]
Broken link to integrations page [here](../blob/master/intro/content/quantum-resources/variational_loop.mdx#template)

**Comment by 1ethanhansen** [comment]
Actually two links, there's another one to optimize_variational_circuit [here](../blob/master/intro/content/quantum-resources/variational_loop.mdx#python-code)

**Comment by jama22** [comment]
I'd say remove the sentance "You can read more about them on the integrations page." entirely

**Comment by jama22** [comment]
@max-radin or @mstechly  do you know what file `optimize_variational_circuit` was supposed to reference?

**Comment by mstechly** [comment]
Good catch – this become obsolete in the recent changes.
Will fix all that!

**Comment by mstechly** [comment]
I've fixed that in #36 .
