### ISSUE TITLE
Broken links in workflow Resources

### ISSUE THREAD

**Issue by 1ethanhansen** [zapatacomputing/orquestra-docs#27]
in the last section, [Referencing a Resource in a Workflow](../blob/master/qe/content/workflow/resources.mdx#referencing-a-resource-in-a-workflow) both links are broken

**Comment by jama22** [comment]
Looks like it should be referencing https://www.orquestra.io/docs/qe/workflow/workflows/#resources instead. You'd probably have to restructure the sentence so it makes sense
