### ISSUE TITLE
orquestra-overview.svg has a minor issue. 

### ISSUE THREAD

**Issue by sabeegrewal** [zapatacomputing/orquestra-docs#29]
The SVG is used in orquestra-docs/intro/content/basics/platform.md. 

The "t" in "qe submit" has a lot of space before it. Easily seen [here](https://raw.githubusercontent.com/zapatacomputing/orquestra-docs/master/intro/content/img/orquestra-overview.svg).

**Comment by jama22** [comment]
Looking at the raw svg, seems like there are some extraneous tags that got dumped between the `submi` and `t`. I'll give it a shot and see if i can fix it without access to the orignal svg!
